name: Destroy terraform aws infra

on:
  workflow_dispatch:
    inputs:
      environment:
        description: 'Environment to run against'
        type: choice
        required: true
        options:
          - dev
          - staging
          - production
        default: 'dev'

jobs:
  terraform:
    name: "Infrastructure Destroy"
    runs-on: ubuntu-latest
    environment: dev
    defaults:
      run:
        working-directory: ./terraform # Path to your Terraform files

    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ vars.AWS_REGION }}

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v3

      - name: Terraform Destroy
        run: terraform destroy -auto-approve
